name: Build and Publish
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Deploy
      id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'zosky'
        reponame: 'ps3commander'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged  
    - name: RouterHack SimLink
      run: |
        cd dist
        ln -s index.html 404.html
        git add 404.html
        git commit -m '404 router hack'
        git push
      shell: bash

  # router_hack:
  #   # needs: build_vue
  #   runs-on: ubuntu-latest
  #   name: Router Hack
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
      
  #     - name: Make simLink
  #       run: ln -s index.html 404.html
  #     - name: Commit
  #       run: git commit -m 'simLink index 404'
  #     - name: Push
  #       run: git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master:gh-pages
