name: Build and Publish
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'zosky'
        reponame: 'ps3commander'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged  
    - id: goTime
      run: |
        cd dist
        ln -s index.html 404.html
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git add -A 404.html
        git commit -m 'simLink index 404'
        git push git@github.com:${{ github.repository }}.git main:gh-pages
