name: Build and Publish
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Deploy
      id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'zosky'
        reponame: 'ps3commander'
        gitname: zoskyCI
        gitemail: zoskyCI@noReply.com
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged  
    - name: make a fresh gitLog.json
      run: scripts/gitLog.sh
    ## merged upstream w/ https://github.com/xRealNeon/VuePagesAction/pull/4 (but not happening yet?)
    - name: RouterHack SimLink
      run: |
        cd dist
        ln -s index.html 404.html
        git add 404.html
        git commit -m '404 router hack'
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master:gh-pages
      shell: bash
